### PR TITLE
fix(goal_passer): Only pass the goal pose

### PR DESCRIPTION
**Pull request by reinzor**
Removed non-trivial goal_passer behavior. This planners should only pass
the goal and not stop the costmap or check for same goals.

Related to https://github.com/ros-planning/navigation_experimental/issues/15

### CODE REVIEW

**Comment by mintar** [comment]
LGTM. @reinzor : Did you test this, and confirmed that it's working? I suspect the check whether a goal had already been sent may have been a workaround for some old buggy behavior in move_base. The code hasn't been touched since 2010, so if your PR makes it work for your use case, I'm in favor of merging it.

**Comment by reinzor** [comment]
Thanks. Yes it has been tested. We are using our fork now.

**Comment by mintar** [comment]
I've thought some more about this and done some experiments.

There are two cases where move_base will send the same goal again to the global planner:

1. If the parameter `planner_frequency` is not 0, move_base will periodically send the same goal again until it is reached.
2. If the local planner fails, move_base will send the same goal again to the global planner.

In both cases, the old behavior of goal_passer didn't make sense. The first case can be controlled by the user by choosing the `planner_frequency` as desired. In the second case, the old behavior prevented move_base from reaching the goal if the local planner failed at least once. Therefore, I'm merging this PR.

**Comment by mintar** [comment]
Oh, and regarding the `costmap_ros_->stop()`: I believe it was meant to stop the costmap to save some CPU cycles, because `goal_passer` doesn't use it. For whatever reason, that doesn't happen though; the line didn't make any difference in my experiments. Therefore I think it's okay to remove that, too. Especially since goal_passer is only useful for debugging anyway, I don't think it's critical to save those CPU cycles.

**Comment by reinzor** [comment]
We are using it in move base flex where you can have multiple local planners loaded. However, due to this call, all other planners also didn't have a costmap ;)

**Comment by mintar** [comment]
Thanks, good to know! :)

**Pull request merged**
