### PR TITLE
Fix many errors in sbpl_lattice_planner

### LINKED ISSUE #5: sbpl_lattice_planner does not compile in hydro
Due to major changes in the [costmap_2d](http://www.ros.org/wiki/costmap_2d) API introduced with hydro (see http://www.ros.org/wiki/hydro/Migration#Navigation_-_Costmap2D) the sbpl_lattice_planner and probably also other packages from navigation_experimental do not compile:

```
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp: In member function ‘virtual void sbpl_lattice_planner::SBPLLatticePlanner::initialize(std::string, costmap_2d::Costmap2DROS*)’:
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:114:19: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘clearRobotFootprint’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:115:19: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getCostmapCopy’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:132:101: error: ‘class costmap_2d::Costmap2D’ has no member named ‘getCircumscribedCost’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:148:47: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getSizeInCellsX’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:149:47: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getSizeInCellsY’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:154:62: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getResolution’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:166:44: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getSizeInCellsX’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:167:46: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getSizeInCellsY’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp: In member function ‘virtual bool sbpl_lattice_planner::SBPLLatticePlanner::makePlan(const PoseStamped&, const PoseStamped&, std::vector<geometry_msgs::PoseStamped_<std::allocator<void> > >&)’:
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:237:17: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘clearRobotFootprint’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:240:17: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getCostmapCopy’
/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/src/sbpl_lattice_planner.cpp:372:44: warning: ‘void tf::Quaternion::setEulerZYX(const tfScalar&, const tfScalar&, const tfScalar&)’ is deprecated (declared at /opt/ros/hydro/include/tf/LinearMath/Quaternion.h:114) [-Wdeprecated-declarations]
make[3]: *** [CMakeFiles/sbpl_lattice_planner.dir/src/sbpl_lattice_planner.cpp.o] Error 1
make[3]: Leaving directory `/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/build'
make[2]: *** [CMakeFiles/sbpl_lattice_planner.dir/all] Error 2
make[2]: Leaving directory `/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/hector/hydro/stacks/external/navigation_experimental/sbpl_lattice_planner/build'
make: *** [all] Error 2
```

Are there any plans to update the hydro-devel branch in near future or should the navigation_experimental stack be considered as deprecated?

### PR DESCRIPTION
**Pull request by mintar**
Supersedes #14 (includes all relevant commits from there)

Includes fixes from @meyerj, @trainman419, @luator and myself from all the various forks of sbpl_lattice_planner .

Closes #5 .

### CODE REVIEW

**Comment by DLu** [comment]
I generally have no idea what's going on here, but trying to compile this fork gets me:
```
  Found package configuration file:

    /opt/ros/kinetic/share/sbpl/sbpl-config.cmake

  but it set SBPL_FOUND to FALSE so package "SBPL" is considered to be NOT
  FOUND.
```

**Comment by mintar** [comment]
Hi @DLu,

I couldn't reproduce your error. I've created a Vagrantfile (see below); if you copy that file into the `sbpl_lattice_planner` subdirectory and run `vagrant up`, you can see that everything compiles smoothly. I've also tried with `catkin_make` instead of `catkin-tools`, it also works.

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  $script = <<-SHELL
    export CI_ROS_DISTRO="kinetic"
    export REPONAME="sbpl_lattice_planner"
    export CATKIN_WS=~/catkin_ws
    export CATKIN_WS_SRC=${CATKIN_WS}/src
    
    # set up ROS repo
    sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list'
    wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    sudo apt-get update -qq
    sudo apt-get install -qq -y python-rosdep python-catkin-tools git build-essential cmake
    sudo rosdep init
    rosdep update
    
    # create a catkin workspace
    mkdir -p $CATKIN_WS_SRC
    cd $CATKIN_WS_SRC
    ln -s /vagrant $CATKIN_WS_SRC/$REPONAME

    # Use rosdep to install all dependencies (including ROS itself)
    rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO
    
    # source setup.bash
    source /opt/ros/$CI_ROS_DISTRO/setup.bash
    cd $CATKIN_WS

    # Init catkin workspace
    catkin init
    # Enable install space
    catkin config --install
    # Build [and Install] packages
    catkin build --limit-status-rate 0.1 --no-notify -DCMAKE_BUILD_TYPE=Release
    # Build tests
    catkin build --limit-status-rate 0.1 --no-notify --make-args tests
    # Run tests
    catkin run_tests

    # catkin_lint
    sudo apt-get install -y python-catkin-lint
    cd $CATKIN_WS_SRC/$REPONAME
    catkin_lint .
  SHELL
  config.vm.provision "shell", inline: $script, privileged: false
end
```

**Comment by mintar** [comment]
Did you maybe forget to run an `apt update && apt upgrade`? SBPL recently released version 1.3.1 as a ROS deb package, so make sure you have that (ros-kinetic-sbpl).

**Comment by mintar** [comment]
If that doesn't fix it, the contents of your `/opt/ros/kinetic/share/sbpl/sbpl-config.cmake` would be interesting.

**Comment by DLu** [comment]
Sorry, I should have done a clean build, which seems to have fixed it.

**Comment by mintar** [comment]
Hmm, it's a shame you squashed all commits in this PR. I cherry-picked those commits from several different forks and spent some time cleaning up the history, and having the commits in there would have made it easier to spot if we already have the commit from that specific fork in here. Anyway, too late now. Thanks for merging!

**Comment by DLu** [comment]
I have used my Git-finity gauntlet to alter the timeline and do a non-squashing merge here: https://github.com/ros-planning/navigation_experimental/commit/cf5e55f18e85d799d3dc5c8ff40af822dba28806

**Comment by mintar** [comment]
Nice! I had thought about this, but I didn't want the first thing I did as a maintainer to be a `git push --force`. It scares people. :D

**Comment by DLu** [comment]
mad with power

**Pull request merged**
